# Generated by Django 4.1.6 on 2023-08-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='product_item',
        ),
    ]
