# Generated by Django 4.1.6 on 2023-08-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_rename_product_review_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_item',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
    ]
