# Generated by Django 4.1.6 on 2023-08-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_alter_product_category_alter_product_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='furniture.product', verbose_name='Продукт'),
        ),
    ]
